-테이블 삭제 명령어-
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;
-----------------삭제------------------
--접속유저의 모든테이블 및 제약조건 삭제

BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/
--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/
--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
---------------------------------------

CREATE TABLE "MEMBER" (
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"USER_ID"	VARCHAR2(100)		NOT NULL,
	"USER_PASSWORD"	VARCHAR2(100)		NOT NULL,
	"USER_TYPE"	NUMBER	DEFAULT 1	NOT NULL,
	"USER_NICK"	VARCHAR2(100)		NULL,
	"USER_NAME"	VARCHAR2(100)		NOT NULL,
	"USER_BRITH"	VARCHAR2(100)		NULL,
	"USER_EMAIL"	VARCHAR2(100)		NULL,
	"USER_PHONE"	VARCHAR2(100)		NOT NULL,
	"USER_ENTERDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_ADDRESS"	VARCHAR2(500)		NULL,
	"USER_ADDRESSNUM"	VARCHAR2(100)		NULL,
	"USER_POINT"	NUMBER		NULL,
	"USER_STATUS"	VARCHAR2(10)	DEFAULT 'Y'	NULL,
	"REASON"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "MEMBER"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."USER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."USER_PASSWORD" IS '회원비밀번호';

COMMENT ON COLUMN "MEMBER"."USER_TYPE" IS '회원종류';

COMMENT ON COLUMN "MEMBER"."USER_NICK" IS '회원별칭';

COMMENT ON COLUMN "MEMBER"."USER_NAME" IS '회원이름';

COMMENT ON COLUMN "MEMBER"."USER_BRITH" IS '회원생년월일';

COMMENT ON COLUMN "MEMBER"."USER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "MEMBER"."USER_PHONE" IS '회원전화번호';

COMMENT ON COLUMN "MEMBER"."USER_ENTERDATE" IS '회원가입일';

COMMENT ON COLUMN "MEMBER"."USER_ADDRESS" IS '회원주소';

COMMENT ON COLUMN "MEMBER"."USER_ADDRESSNUM" IS '우편번호';

COMMENT ON COLUMN "MEMBER"."USER_POINT" IS '보유포인트';

COMMENT ON COLUMN "MEMBER"."USER_STATUS" IS '회원상태';

COMMENT ON COLUMN "MEMBER"."REASON" IS '탈퇴사유';



CREATE TABLE "CATEGORY_TYPE" (
	"PROJECT_CATEGORY"	VARCHAR2(10)		NOT NULL,
	"PROJECT_NAME"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "CATEGORY_TYPE"."PROJECT_CATEGORY" IS '프로젝트타입번호';

COMMENT ON COLUMN "CATEGORY_TYPE"."PROJECT_NAME" IS '프로젝트타입이름';



CREATE TABLE "FUNDING_LIST" (
	"FUNDING_NO"	VARCHAR2(10)		NOT NULL,
	"REWARD_NO"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"FUNDING_PRODUCT"	VARCHAR2(100)		NULL,
	"FUNDING_COST"	NUMBER		NULL,
	"FUNDING_QUANTITY"	NUMBER		NULL,
	"FUNDING_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"FUNDING_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL,
	"PAYMENT_METHOD"	VARCHAR2(100)		NULL,
	"FUNDING_SPONSERSHIP"	NUMBER		NULL
);

COMMENT ON COLUMN "FUNDING_LIST"."FUNDING_NO" IS '펀딩번호';

COMMENT ON COLUMN "FUNDING_LIST"."REWARD_NO" IS '리워드번호';

COMMENT ON COLUMN "FUNDING_LIST"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "FUNDING_LIST"."FUNDING_PRODUCT" IS '펀딩해서받은제품';

COMMENT ON COLUMN "FUNDING_LIST"."FUNDING_COST" IS '펀딩금액';

COMMENT ON COLUMN "FUNDING_LIST"."FUNDING_QUANTITY" IS '펀딩수량';

COMMENT ON COLUMN "FUNDING_LIST"."FUNDING_DATE" IS '펀딩일자';

COMMENT ON COLUMN "FUNDING_LIST"."FUNDING_STATUS" IS '펀딩상태';

COMMENT ON COLUMN "FUNDING_LIST"."PAYMENT_METHOD" IS '결제방식';

COMMENT ON COLUMN "FUNDING_LIST"."FUNDING_SPONSERSHIP" IS '후원금';



CREATE TABLE "PROJECT" (
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"PROJECT_CATEGORY"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"PROJECT_NAME"	VARCHAR2(100)		NULL,
	"PROJECT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"PROJECT_STARTDATE"	DATE		NULL,
	"PROJECT_FINISHDATE"	DATE		NULL,
	"PROJECT_CONTENT"	CLOB		NULL,
	"PROJECT_TARGET_AMOUNT"	NUMBER		NULL,
	"PROJECT_REPORT"	NUMBER		NULL,
	"HASHTAGS"	VARCHAR2(500)		NULL,
	"PROJECT_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL,
	"STATUS_STORY"	VARCHAR2(1)		NULL
);

COMMENT ON COLUMN "PROJECT"."PROJECT_NUMBER" IS '프로젝트번호';

COMMENT ON COLUMN "PROJECT"."PROJECT_CATEGORY" IS '프로젝트타입번호';

COMMENT ON COLUMN "PROJECT"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "PROJECT"."PROJECT_NAME" IS '프로젝트이름';

COMMENT ON COLUMN "PROJECT"."PROJECT_DATE" IS '프로젝트 저장일';

COMMENT ON COLUMN "PROJECT"."PROJECT_STARTDATE" IS '프로젝트시작일';

COMMENT ON COLUMN "PROJECT"."PROJECT_FINISHDATE" IS '프로젝트종료일';

COMMENT ON COLUMN "PROJECT"."PROJECT_CONTENT" IS '프로젝트내용';

COMMENT ON COLUMN "PROJECT"."PROJECT_TARGET_AMOUNT" IS '프로젝트목표금액';

COMMENT ON COLUMN "PROJECT"."PROJECT_REPORT" IS '신고당한횟수';

COMMENT ON COLUMN "PROJECT"."HASHTAGS" IS '해시태그들';

COMMENT ON COLUMN "PROJECT"."PROJECT_STATUS" IS '프로젝트상태값';

COMMENT ON COLUMN "PROJECT"."STATUS_STORY" IS '스토리상태값';



CREATE TABLE "FAQ" (
	"FAQ_NO"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"FAQ_TITLE"	VARCHAR2(500)		NULL,
	"FAQ_ANSWER"	VARCHAR2(500)		NULL,
	"FAQ_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "FAQ"."FAQ_NO" IS 'FAQ번호';

COMMENT ON COLUMN "FAQ"."USER_NO" IS '회원번호.작성자';

COMMENT ON COLUMN "FAQ"."FAQ_TITLE" IS '질문제목';

COMMENT ON COLUMN "FAQ"."FAQ_ANSWER" IS 'FAQ답변';

COMMENT ON COLUMN "FAQ"."FAQ_STATUS" IS '상태값';



CREATE TABLE "NOTICE_TEMP" (
	"NOTICE_NO"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(100)		NULL,
	"NOTICE_CONTENT"	CLOB		NULL,
	"NOTICE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"NOTICE_COUNT"	NUMBER		NULL,
	"NOTICE_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "NOTICE_TEMP"."NOTICE_NO" IS '공지번호';

COMMENT ON COLUMN "NOTICE_TEMP"."USER_NO" IS '회원번호.작성자';

COMMENT ON COLUMN "NOTICE_TEMP"."NOTICE_TITLE" IS '공지제목';

COMMENT ON COLUMN "NOTICE_TEMP"."NOTICE_CONTENT" IS '공지내용';

COMMENT ON COLUMN "NOTICE_TEMP"."NOTICE_DATE" IS '작성일';

COMMENT ON COLUMN "NOTICE_TEMP"."NOTICE_COUNT" IS '조회수';

COMMENT ON COLUMN "NOTICE_TEMP"."NOTICE_STATUS" IS '상태값';



CREATE TABLE "ATTACHMENT" (
	"FILE_NO"	VARCHAR2(10)		NOT NULL,
	"REF_NO"	VARCHAR2(10)		NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL,
	"FILE_PATH"	VARCHAR2(4000)		NULL,
	"UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"FILE_LEVEL"	NUMBER		NULL,
	"STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "ATTACHMENT"."FILE_NO" IS '파일번호';

COMMENT ON COLUMN "ATTACHMENT"."REF_NO" IS '참조번호';

COMMENT ON COLUMN "ATTACHMENT"."ORIGIN_NAME" IS '원본';

COMMENT ON COLUMN "ATTACHMENT"."CHANGE_NAME" IS '변경';

COMMENT ON COLUMN "ATTACHMENT"."FILE_PATH" IS '경로';

COMMENT ON COLUMN "ATTACHMENT"."UPLOAD_DATE" IS '날짜';

COMMENT ON COLUMN "ATTACHMENT"."FILE_LEVEL" IS '파일레벨';

COMMENT ON COLUMN "ATTACHMENT"."STATUS" IS '상태값';



CREATE TABLE "REPLY_ANSWER" (
	"ANS_NO"	VARCHAR2(10)		NOT NULL,
	"QUESETION_NUMBER"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"ANS_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"ANS_CONTENT"	VARCHAR2(100)		NULL,
	"ANS_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL,
	"ANS_BAN_COUNT"	NUMBER	DEFAULT 0	NULL
);

COMMENT ON COLUMN "REPLY_ANSWER"."ANS_NO" IS '답변번호';

COMMENT ON COLUMN "REPLY_ANSWER"."QUESETION_NUMBER" IS '문의번호';

COMMENT ON COLUMN "REPLY_ANSWER"."USER_NO" IS '회원번호,답변해준사람';

COMMENT ON COLUMN "REPLY_ANSWER"."ANS_DATE" IS '답변날짜';

COMMENT ON COLUMN "REPLY_ANSWER"."ANS_CONTENT" IS '답변내용';

COMMENT ON COLUMN "REPLY_ANSWER"."ANS_STATUS" IS '상태값';

COMMENT ON COLUMN "REPLY_ANSWER"."ANS_BAN_COUNT" IS '답변 신고 횟수';


CREATE TABLE "REWARD" (
	"REWARD_NO"	VARCHAR2(10)		NOT NULL,
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"REWARD_TITLE"	VARCHAR2(100)		NULL,
	"REWARD_CONTENT"	VARCHAR2(4000)		NULL,
	"REWARD_COST"	NUMBER		NULL,
	"REWARD_REMAINING_QUANTITY"	NUMBER		NULL,
	"REWARD_DELIVERY_COST"	NUMBER	DEFAULT 3000	NULL,
	"REWARD_STATUS"	VARCHAR2(1)		NULL
);

COMMENT ON COLUMN "REWARD"."REWARD_NO" IS '리워드번호';

COMMENT ON COLUMN "REWARD"."PROJECT_NUMBER" IS '프로젝트번호';

COMMENT ON COLUMN "REWARD"."REWARD_TITLE" IS '리워드제목';

COMMENT ON COLUMN "REWARD"."REWARD_CONTENT" IS '리워드내용';

COMMENT ON COLUMN "REWARD"."REWARD_COST" IS '리워드내용';

COMMENT ON COLUMN "REWARD"."REWARD_REMAINING_QUANTITY" IS '상품잔여량';

COMMENT ON COLUMN "REWARD"."REWARD_DELIVERY_COST" IS '배송비';



CREATE TABLE "WISHLIST" (
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"WISHLIST_DATE"	DATE		NULL,
	"WISHLIST_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "WISHLIST"."PROJECT_NUMBER" IS '프로젝트번호';

COMMENT ON COLUMN "WISHLIST"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "WISHLIST"."WISHLIST_DATE" IS '찜한날짜';

COMMENT ON COLUMN "WISHLIST"."WISHLIST_STATUS" IS '상태값';



CREATE TABLE "EVENT" (
	"EVENT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"EVENT_CONTENT"	CLOB		NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"EVENT_TITLE"	VARCHAR2(100)		NULL,
	"EVENT_DATE"	DATE		NULL,
	"EVENT_COUNT"	NUMBER		NULL,
	"EVENT_STARTDATE"	DATE		NULL,
	"EVENT_ENDDATE"	DATE		NULL,
	"EVENT_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "EVENT"."EVENT_NUMBER" IS '게시글번호';

COMMENT ON COLUMN "EVENT"."EVENT_CONTENT" IS '이벤트내용';

COMMENT ON COLUMN "EVENT"."USER_NO" IS '회원번호.작성자';

COMMENT ON COLUMN "EVENT"."EVENT_TITLE" IS '이벤트제목';

COMMENT ON COLUMN "EVENT"."EVENT_DATE" IS '작성일';

COMMENT ON COLUMN "EVENT"."EVENT_COUNT" IS '조회수';

COMMENT ON COLUMN "EVENT"."EVENT_STARTDATE" IS '이벤트시작일';

COMMENT ON COLUMN "EVENT"."EVENT_ENDDATE" IS '이벤트종료일';

COMMENT ON COLUMN "EVENT"."EVENT_STATUS" IS '상태값';



CREATE TABLE "PAYMENT" (
	"PAY_NO"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"PAY_NAME"	VARCHAR2(50)		NULL,
	"PAY_EMAIL"	VARCHAR2(50)		NULL,
	"PAY_PHONE"	VARCHAR2(50)		NULL,
	"PAY_DATE"	DATE		NULL,
	"PAY_RESERVE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"CARD_NO"	VARCHAR2(19)		NULL,
	"CARD_V_DATE"	VARCHAR2(5)		NULL,
	"CARD_CVC"	VARCHAR2(3)		NULL
);

COMMENT ON COLUMN "PAYMENT"."PAY_NO" IS '결제번호';

COMMENT ON COLUMN "PAYMENT"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "PAYMENT"."PROJECT_NUMBER" IS '프로젝트번호';

COMMENT ON COLUMN "PAYMENT"."PAY_NAME" IS '결제이름';

COMMENT ON COLUMN "PAYMENT"."PAY_EMAIL" IS '결제이메일';

COMMENT ON COLUMN "PAYMENT"."PAY_PHONE" IS '결제연락처';

COMMENT ON COLUMN "PAYMENT"."PAY_DATE" IS '결제일자';

COMMENT ON COLUMN "PAYMENT"."PAY_RESERVE_DATE" IS '예약일자';

COMMENT ON COLUMN "PAYMENT"."CARD_NO" IS '카드번호';

COMMENT ON COLUMN "PAYMENT"."CARD_V_DATE" IS '카드유효기간';

COMMENT ON COLUMN "PAYMENT"."CARD_CVC" IS '카드CVC';



CREATE TABLE "NEWS" (
	"NEWS_NO"	VARCHAR2(10)		NOT NULL,
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"NEWS_TITLE"	VARCHAR2(100)		NULL,
	"NEWS_CONTENT"	CLOB		NULL,
	"NEWS_DATE"	DATE		NULL,
	"NEWS_COUNT"	NUMBER	DEFAULT 0	NULL,
	"NEWS_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "NEWS"."NEWS_NO" IS '새소식번호';

COMMENT ON COLUMN "NEWS"."PROJECT_NUMBER" IS '프로젝트번호';

COMMENT ON COLUMN "NEWS"."NEWS_TITLE" IS '새소식제목';

COMMENT ON COLUMN "NEWS"."NEWS_CONTENT" IS '새소식내용';

COMMENT ON COLUMN "NEWS"."NEWS_DATE" IS '작성일';

COMMENT ON COLUMN "NEWS"."NEWS_COUNT" IS '조회수';

COMMENT ON COLUMN "NEWS"."NEWS_STATUS" IS '상태값';



CREATE TABLE "BAN_LIST" (
	"BAN_NO"	VARCHAR(10)		NOT NULL,
	"REPORT_NO"	VARCHAR2(10)		NOT NULL,
	"BAN_COUNT"	NUMBER		NULL,
	"BAN_CATEGORY"	NUMBER		NULL,
	"BAN_STATUS"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "BAN_LIST"."BAN_NO" IS '블랙번호';

COMMENT ON COLUMN "BAN_LIST"."REPORT_NO" IS '의견번호,프젝번호 (여기에  조인하면정보 다끌어쓸수있음)';

COMMENT ON COLUMN "BAN_LIST"."BAN_COUNT" IS '신고카운팅';

COMMENT ON COLUMN "BAN_LIST"."BAN_CATEGORY" IS '새소식=1,프로젝트=2';

COMMENT ON COLUMN "BAN_LIST"."BAN_STATUS" IS '이걸로 게시글 있는지 없는지';



CREATE TABLE "REPORT" (
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"REPORT_NO"	VARCHAR2(10)		NOT NULL,
	"REPORT_CATEGORY"	VARCHAR2(10)		NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"REPORT_TITLE"	VARCHAR2(100)		NULL,
	"REPORT_CONTENT"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "REPORT"."USER_NO" IS '회원번호.신고한사람';

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호.신고된새소식 또는 신고된프로젝트번호';

COMMENT ON COLUMN "REPORT"."REPORT_CATEGORY" IS '새소식=1, 프로젝트=2';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고날짜';

COMMENT ON COLUMN "REPORT"."REPORT_TITLE" IS '신고제목';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고내용';



CREATE TABLE "TB_OPTION" (
	"REWARD_NO"	VARCHAR2(10)		NOT NULL,
	"ITEM_NO"	VARCHAR2(10)		NOT NULL,
	"ITEM_QUANTITY"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "TB_OPTION"."REWARD_NO" IS '리워드번호';

COMMENT ON COLUMN "TB_OPTION"."ITEM_NO" IS '아이템번호';

COMMENT ON COLUMN "TB_OPTION"."ITEM_QUANTITY" IS '아이템수량';



CREATE TABLE "PROJECT_BASIC" (
	"PROJECT_BASIC_NO"	VARCHAR2(10)		NOT NULL,
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"ANSWER1"	VARCHAR2(1000)		NULL,
	"ANSWER2"	VARCHAR2(1000)		NULL,
	"ANSWER3"	VARCHAR2(1000)		NULL,
	"ANSWER4"	VARCHAR2(1000)		NULL,
	"CHECK1"	VARCHAR2(10)		NULL,
	"CHECK2"	VARCHAR2(10)		NULL,
	"STATUS"	VARCHAR2(1)		NULL
);

COMMENT ON COLUMN "PROJECT_BASIC"."PROJECT_BASIC_NO" IS '프로젝트기본번호';

COMMENT ON COLUMN "PROJECT_BASIC"."PROJECT_NUMBER" IS '프로젝트번호';

COMMENT ON COLUMN "PROJECT_BASIC"."ANSWER1" IS '답변저장';

COMMENT ON COLUMN "PROJECT_BASIC"."ANSWER2" IS '답변저장';

COMMENT ON COLUMN "PROJECT_BASIC"."ANSWER3" IS '답변저장';

COMMENT ON COLUMN "PROJECT_BASIC"."ANSWER4" IS '답변저장';

COMMENT ON COLUMN "PROJECT_BASIC"."CHECK1" IS '체크저장';

COMMENT ON COLUMN "PROJECT_BASIC"."CHECK2" IS '체크저장';

COMMENT ON COLUMN "PROJECT_BASIC"."STATUS" IS '상태값';



CREATE TABLE "PROJECT_MAKER" (
	"MAKER_NO"	VARCHAR(255)		NOT NULL,
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"MAKER_NAME"	VARCHAR2(100)		NULL,
	"MAKER_EMAIL"	VARCHAR2(100)		NULL,
	"MAKER_PHONE"	VARCHAR2(100)		NULL,
	"MAKER_TYPE"	VARCHAR2(100)		NULL,
	"REPRESENTATIVE_NAME"	VARCHAR2(100)		NULL,
	"REPRESENTATIVE_EMAIL"	VARCHAR2(100)		NULL,
	"STATUS"	VARCHAR2(1)		NULL
);

COMMENT ON COLUMN "PROJECT_MAKER"."MAKER_NO" IS '메이커번호';

COMMENT ON COLUMN "PROJECT_MAKER"."PROJECT_NUMBER" IS '프로젝트번호';

COMMENT ON COLUMN "PROJECT_MAKER"."MAKER_NAME" IS '메이커명';

COMMENT ON COLUMN "PROJECT_MAKER"."MAKER_EMAIL" IS '이메일';

COMMENT ON COLUMN "PROJECT_MAKER"."MAKER_PHONE" IS '전화번호';

COMMENT ON COLUMN "PROJECT_MAKER"."MAKER_TYPE" IS '사업자구분';

COMMENT ON COLUMN "PROJECT_MAKER"."REPRESENTATIVE_NAME" IS '대표자명';

COMMENT ON COLUMN "PROJECT_MAKER"."REPRESENTATIVE_EMAIL" IS '대표자이메일';

COMMENT ON COLUMN "PROJECT_MAKER"."STATUS" IS '상태값';



CREATE TABLE "ITEM" (
	"ITEM_NO"	VARCHAR2(10)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100)		NULL,
	"PROJECT_NUMBER"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "ITEM"."ITEM_NO" IS '아이템번호';

COMMENT ON COLUMN "ITEM"."ITEM_NAME" IS '아이템명';

COMMENT ON COLUMN "ITEM"."PROJECT_NUMBER" IS '프로젝트번호';



CREATE TABLE "PERSON_QUESTION" (
	"A_QUESTION_NO"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"QUESTION_TYPE"	NUMBER		NOT NULL,
	"QUESTION_TITLE"	VARCHAR2(100)		NULL,
	"QUESTION_CONTENT"	VARCHAR2(4000)		NULL,
	"QUESTION_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"QUESTION_YN"	VARCHAR2(10)	DEFAULT 'N'	NULL,
	"QUESTION_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL,
	"ANS_TITLE"	VARCHAR2(100)		NULL,
	"ANS_CONTENT"	VARCHAR2(100)		NULL,
	"ANS_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"ANS_NO"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "PERSON_QUESTION"."A_QUESTION_NO" IS '의견번호';

COMMENT ON COLUMN "PERSON_QUESTION"."USER_NO" IS '회원번호.작성자';

COMMENT ON COLUMN "PERSON_QUESTION"."QUESTION_TYPE" IS '답변자(1, 등록자 / 2. 관리자)';

COMMENT ON COLUMN "PERSON_QUESTION"."QUESTION_TITLE" IS '의견제목';

COMMENT ON COLUMN "PERSON_QUESTION"."QUESTION_CONTENT" IS '의견내용';

COMMENT ON COLUMN "PERSON_QUESTION"."QUESTION_DATE" IS '문의등록날짜';

COMMENT ON COLUMN "PERSON_QUESTION"."QUESTION_YN" IS '의견여부';

COMMENT ON COLUMN "PERSON_QUESTION"."QUESTION_STATUS" IS '상태값';

COMMENT ON COLUMN "PERSON_QUESTION"."ANS_TITLE" IS '답변제목';

COMMENT ON COLUMN "PERSON_QUESTION"."ANS_CONTENT" IS '답변내용';

COMMENT ON COLUMN "PERSON_QUESTION"."ANS_DATE" IS '답변날짜';

COMMENT ON COLUMN "PERSON_QUESTION"."ANS_NO" IS '회원번호.답변자';



CREATE TABLE "REPLY" (
	"P_QUESTION_NO"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NOT NULL,
	"QUESTION_CONTENT"	VARCHAR2(4000)		NULL,
	"QUESTION_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"QUESTION_YN"	VARCHAR2(10)	DEFAULT 'N'	NULL,
	"QUESTION_STATUS"	VARCHAR2(10)	DEFAULT 'N'	NULL,
	"QUESTION_BAN_COUNT"	NUMBER	DEFAULT 0	NULL
);

COMMENT ON COLUMN "REPLY"."P_QUESTION_NO" IS '의견번호';

COMMENT ON COLUMN "REPLY"."USER_NO" IS '회원번호.작성자';

COMMENT ON COLUMN "REPLY"."QUESTION_CONTENT" IS '의견내용';

COMMENT ON COLUMN "REPLY"."QUESTION_DATE" IS '문의등록날짜';

COMMENT ON COLUMN "REPLY"."QUESTION_YN" IS '의견여부';

COMMENT ON COLUMN "REPLY"."QUESTION_STATUS" IS '상태값';

COMMENT ON COLUMN "REPLY"."QUESTION_BAN_COUNT" IS '의견단 댓글 신고횟수';



CREATE TABLE "STATISTICS" (
	"STATISTICS_NO"	VARCHAR2(10)		NOT NULL,
	"USER_NO"	VARCHAR2(10)		NULL,
	"STATISTICS_DAY"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "STATISTICS"."STATISTICS_NO" IS '통계번호';

COMMENT ON COLUMN "STATISTICS"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "STATISTICS"."STATISTICS_DAY" IS '날짜';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "CATEGORY_TYPE" ADD CONSTRAINT "PK_CATEGORY_TYPE" PRIMARY KEY (
	"PROJECT_CATEGORY"
);

ALTER TABLE "FUNDING_LIST" ADD CONSTRAINT "PK_FUNDING_LIST" PRIMARY KEY (
	"FUNDING_NO"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY (
	"PROJECT_NUMBER"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"FAQ_NO"
);

ALTER TABLE "NOTICE_TEMP" ADD CONSTRAINT "PK_NOTICE_TEMP" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "REPLY_ANSWER" ADD CONSTRAINT "PK_REPLY_ANSWER" PRIMARY KEY (
	"ANS_NO"
);

ALTER TABLE "REWARD" ADD CONSTRAINT "PK_REWARD" PRIMARY KEY (
	"REWARD_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"PROJECT_NUMBER",
	"USER_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVENT_NUMBER"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAY_NO",
	"USER_NO"
);

ALTER TABLE "NEWS" ADD CONSTRAINT "PK_NEWS" PRIMARY KEY (
	"NEWS_NO"
);

ALTER TABLE "BAN_LIST" ADD CONSTRAINT "PK_BAN_LIST" PRIMARY KEY (
	"BAN_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"USER_NO",
	"REPORT_NO"
);

ALTER TABLE "TB_OPTION" ADD CONSTRAINT "PK_OPTION" PRIMARY KEY (
	"REWARD_NO",
	"ITEM_NO"
);

ALTER TABLE "PROJECT_BASIC" ADD CONSTRAINT "PK_PROJECT_BASIC" PRIMARY KEY (
	"PROJECT_BASIC_NO"
);

ALTER TABLE "PROJECT_MAKER" ADD CONSTRAINT "PK_PROJECT_MAKER" PRIMARY KEY (
	"MAKER_NO"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY (
	"ITEM_NO"
);

ALTER TABLE "PERSON_QUESTION" ADD CONSTRAINT "PK_PERSON_QUESTION" PRIMARY KEY (
	"A_QUESTION_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"P_QUESTION_NO"
);

ALTER TABLE "STATISTICS" ADD CONSTRAINT "PK_STATISTICS" PRIMARY KEY (
	"STATISTICS_NO"
);

ALTER TABLE "FUNDING_LIST" ADD CONSTRAINT "FK_REWARD_TO_FUNDING_LIST_1" FOREIGN KEY (
	"REWARD_NO"
)
REFERENCES "REWARD" (
	"REWARD_NO"
);

ALTER TABLE "FUNDING_LIST" ADD CONSTRAINT "FK_MEMBER_TO_FUNDING_LIST_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "FK_CATEGORY_TYPE_TO_PROJECT_1" FOREIGN KEY (
	"PROJECT_CATEGORY"
)
REFERENCES "CATEGORY_TYPE" (
	"PROJECT_CATEGORY"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "FK_MEMBER_TO_PROJECT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "FK_MEMBER_TO_FAQ_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "NOTICE_TEMP" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_TEMP_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "REPLY_ANSWER" ADD CONSTRAINT "FK_REPLY_TO_REPLY_ANSWER_1" FOREIGN KEY (
	"QUESETION_NUMBER"
)
REFERENCES "REPLY" (
	"P_QUESTION_NO"
);

ALTER TABLE "REPLY_ANSWER" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_ANSWER_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "REWARD" ADD CONSTRAINT "FK_PROJECT_TO_REWARD_1" FOREIGN KEY (
	"PROJECT_NUMBER"
)
REFERENCES "PROJECT" (
	"PROJECT_NUMBER"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_PROJECT_TO_WISHLIST_1" FOREIGN KEY (
	"PROJECT_NUMBER"
)
REFERENCES "PROJECT" (
	"PROJECT_NUMBER"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBER_TO_WISHLIST_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "FK_MEMBER_TO_EVENT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_MEMBER_TO_PAYMENT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_PROJECT_TO_PAYMENT_1" FOREIGN KEY (
	"PROJECT_NUMBER"
)
REFERENCES "PROJECT" (
	"PROJECT_NUMBER"
);

ALTER TABLE "NEWS" ADD CONSTRAINT "FK_PROJECT_TO_NEWS_1" FOREIGN KEY (
	"PROJECT_NUMBER"
)
REFERENCES "PROJECT" (
	"PROJECT_NUMBER"
);

ALTER TABLE "TB_OPTION" ADD CONSTRAINT "FK_REWARD_TO_TB_OPTION_1" FOREIGN KEY (
	"REWARD_NO"
)
REFERENCES "REWARD" (
	"REWARD_NO"
);

ALTER TABLE "TB_OPTION" ADD CONSTRAINT "FK_ITEM_TO_TB_OPTION_1" FOREIGN KEY (
	"ITEM_NO"
)
REFERENCES "ITEM" (
	"ITEM_NO"
);

ALTER TABLE "PROJECT_BASIC" ADD CONSTRAINT "FK_PROJECT_TO_PROJECT_BASIC_1" FOREIGN KEY (
	"PROJECT_NUMBER"
)
REFERENCES "PROJECT" (
	"PROJECT_NUMBER"
);

ALTER TABLE "PROJECT_MAKER" ADD CONSTRAINT "FK_PROJECT_TO_PROJECT_MAKER_1" FOREIGN KEY (
	"PROJECT_NUMBER"
)
REFERENCES "PROJECT" (
	"PROJECT_NUMBER"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "FK_PROJECT_TO_ITEM_1" FOREIGN KEY (
	"PROJECT_NUMBER"
)
REFERENCES "PROJECT" (
	"PROJECT_NUMBER"
);

ALTER TABLE "PERSON_QUESTION" ADD CONSTRAINT "FK_MEMBER_TO_PERSON_QUESTION_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "STATISTICS" ADD CONSTRAINT "FK_MEMBER_TO_STATISTICS_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

